export{default as About} from "./About"
export{default as Nav} from "./Nav"
export{default as Shop} from "./Shop"
export {default as ErrorPage} from "./ErrorPage"
export{default as Home} from "./Home"